language: php

matrix:
  include:
    - php: 7.0
      env: BROADWAY=^1
    - php: 7.1
      env: BROADWAY=^1
    - php: 7.2
      env: BROADWAY=^1
    - php: 7.3
      env: BROADWAY=^1
    - php: 7.0
      env: BROADWAY=^2.1
    - php: 7.1
      env: BROADWAY=^2.1
    - php: 7.2
      env: BROADWAY=^2.1
    - php: 7.3
      env: BROADWAY=^2.1

before_script:
  - composer selfupdate
  - composer require broadway/broadway $BROADWAY
  - composer update --prefer-dist

script:
  - vendor/bin/phpunit
  - vendor/bin/phpbench run --report=default


after_script:
  - vendor/bin/coveralls

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
