language: php

jobs:
  include:
    - php: 7.4
      env: BROADWAY=^2.1
    - php: 8.0
      env: BROADWAY=^2.4

before_script:
  - composer selfupdate
  - composer require broadway/broadway $BROADWAY --prefer-dist

script:
  - vendor/bin/phpunit
  - vendor/bin/phpbench run --report=default

after_script:
  - vendor/bin/coveralls

cache:
  directories:
    - $HOME/.composer/cache
