language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3

before_script:
  - composer selfupdate
  - composer update --prefer-dist

script:
  - vendor/bin/phpunit
  - vendor/bin/phpbench run --report=default


after_script:
  - vendor/bin/coveralls

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
